export let new_label_list=[
    {
        name:"微博",
        img:"http://blog.fengfengzhidao.com/static/news/weibo.png",
    },
    {
        name:"知乎",
        img:"http://blog.fengfengzhidao.com/static/news/zhihu.png",
    },
    {
        name:"微信",
        img:"http://blog.fengfengzhidao.com/static/news/weixin.png",
    },
    {
        name:"百度",
        img:"http://blog.fengfengzhidao.com/static/news/baidu.png",
    },
    {
        name:"36氪",
        img:"http://blog.fengfengzhidao.com/static/news/36ker.png",
    },
    {
        name:"哔哩哔哩",
        img:"http://blog.fengfengzhidao.com/static/news/bilibili.png",
    },
    {
        name:"抖音",
        img:"http://blog.fengfengzhidao.com/static/news/douyin.png",
    },
    {
        name:"拼多多",
        img:"http://blog.fengfengzhidao.com/static/news/pingduoduo.png",
    },
]